apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "predictive-maintenance.configMapName" . }}
  labels:
    {{- include "predictive-maintenance.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
